import { Client } from "@modelcontextprotocol/sdk/client/index.js";
import { InMemoryTransport } from "@modelcontextprotocol/sdk/inMemory.js";
import { ToolListChangedNotificationSchema } from "@modelcontextprotocol/sdk/types.js";
import { describe, expect, it } from "vitest";
import { AppServerMethodCatalog } from "../src/application/app-server-method-catalog.js";
import {
  ResponsesNativeToolCatalog,
  ResponsesNativeToolExecutor,
} from "../src/application/responses-native-tool-catalog.js";
import { createOmniCodexMcpServer } from "../src/infrastructure/mcp/omnicodex-mcp-server.js";
import type { ResponsesNativeToolSpec } from "../src/infrastructure/runtime/responses-loopback-driver.js";

describe("OmniCodex MCP server", () => {
  it("lists only discovered tools on the full surface and routes a native call", async () => {
    const calls: Array<{ method: string; params: unknown }> = [];
    const appServer = {
      request: async <T>(method: string, params: unknown): Promise<T> => {
        calls.push({ method, params });
        if (method === "mcpServerStatus/list") {
          return {
            data: [
              {
                name: "demo",
                tools: {
                  "demo.echo": {
                    name: "demo.echo",
                    description: "Echo a value",
                    inputSchema: {
                      type: "object",
                      properties: { value: { type: "string" } },
                      required: ["value"],
                    },
                  },
                },
              },
            ],
            nextCursor: null,
          } as T;
        }
        if (method === "thread/start") {
          return { thread: { id: "urn:uuid:ephemeral" } } as T;
        }
        if (method === "mcpServer/tool/call") {
          return { content: [{ type: "text", text: "echoed" }] } as T;
        }
        throw new Error(`unexpected method ${method}`);
      },
    };
    const handle = createOmniCodexMcpServer({ appServer });
    const [clientTransport, serverTransport] = InMemoryTransport.createLinkedPair();
    const client = new Client({ name: "test-client", version: "1.0.0" });
    await handle.server.connect(serverTransport);
    await client.connect(clientTransport);

    const listed = await client.listTools();
    expect(listed.tools.map((tool) => tool.name)).toEqual(["demo.echo"]);
    expect(listed.tools[0]?._meta?.omnicodex).toMatchObject({
      nativeName: "demo.echo",
      nativeNamespace: "demo",
      kind: "mcp",
      route: "downstream_direct",
      modelEffect: "none",
    });
    expect(objectValue(listed.tools[0]?._meta?.omnicodex).catalogRevision).toMatch(
      /^[a-f0-9]{64}$/,
    );

    const result = await client.callTool({ name: "demo.echo", arguments: { value: "hello" } });
    expect(result.content).toEqual([{ type: "text", text: "echoed" }]);
    expect(calls.map((call) => call.method)).toEqual([
      "mcpServerStatus/list",
      "thread/start",
      "mcpServer/tool/call",
    ]);

    await client.close();
    await handle.server.close();
  });

  it("blocks a model-backed RPC unless explicitly opted in", async () => {
    const appServer = {
      request: async <T>(method: string): Promise<T> => {
        if (method === "mcpServerStatus/list") {
          return { data: [], nextCursor: null } as T;
        }
        throw new Error("model call should not reach the runtime");
      },
    };
    const appServerMethodCatalog = new AppServerMethodCatalog({
      loadClientRequestSchema: async () => ({
        oneOf: [
          {
            properties: {
              method: { enum: ["turn/start"] },
              params: { type: "object", additionalProperties: true },
            },
          },
        ],
      }),
    });
    const handle = createOmniCodexMcpServer({
      appServer,
      appServerMethodCatalog,
      surface: "compat",
    });
    const [clientTransport, serverTransport] = InMemoryTransport.createLinkedPair();
    const client = new Client({ name: "test-client", version: "1.0.0" });
    await handle.server.connect(serverTransport);
    await client.connect(clientTransport);

    const result = await client.callTool({
      name: "app_server_rpc",
      arguments: { method: "turn/start", params: {} },
    });
    expect(result.isError).toBe(true);
    expect(result.content).toEqual([{ type: "text", text: "MODEL_INVOCATION_NOT_EXPLICIT" }]);

    await client.close();
    await handle.server.close();
  });

  it("lists and directly calls methods generated by the installed App Server schema", async () => {
    const calls: Array<{ method: string; params: unknown }> = [];
    const appServer = {
      request: async <T>(method: string, params: unknown): Promise<T> => {
        calls.push({ method, params });
        if (method === "mcpServerStatus/list") {
          return { data: [], nextCursor: null } as T;
        }
        if (method === "fs/readFile") {
          return { data: "native" } as T;
        }
        throw new Error(`unexpected method ${method}`);
      },
    };
    const appServerMethodCatalog = new AppServerMethodCatalog({
      loadClientRequestSchema: async () => ({
        definitions: {
          FsReadFileParams: {
            type: "object",
            properties: { path: { type: "string" } },
            required: ["path"],
          },
        },
        oneOf: [
          {
            title: "Fs/readFileRequest",
            properties: {
              method: { enum: ["fs/readFile"] },
              params: { $ref: "#/definitions/FsReadFileParams" },
            },
          },
        ],
      }),
    });
    const handle = createOmniCodexMcpServer({ appServer, appServerMethodCatalog });
    const [clientTransport, serverTransport] = InMemoryTransport.createLinkedPair();
    const client = new Client({ name: "test-client", version: "1.0.0" });
    await handle.server.connect(serverTransport);
    await client.connect(clientTransport);

    const listed = await client.listTools();
    const nativeMethod = listed.tools.find(
      (tool) => objectValue(tool._meta?.omnicodex).nativeName === "fs/readFile",
    );
    if (nativeMethod === undefined) throw new Error("missing App Server method tool");
    const result = await client.callTool({
      name: nativeMethod.name,
      arguments: { path: "C:\\workspace\\file.txt" },
    });
    expect(result.structuredContent).toEqual({ data: "native" });
    expect(calls).toContainEqual({
      method: "fs/readFile",
      params: { path: "C:\\workspace\\file.txt" },
    });

    await client.close();
    await handle.server.close();
  });

  it("lists and calls the Responses custom surface without a model", async () => {
    const selected: unknown[] = [];
    const appServer = {
      request: async <T>(method: string): Promise<T> => {
        if (method === "mcpServerStatus/list") {
          return { data: [], nextCursor: null } as T;
        }
        throw new Error(`unexpected method ${method}`);
      },
    };
    const responsesSource = {
      snapshot: {
        refreshedAtUnixMs: 1,
        requestCount: 1,
        tools: [
          {
            type: "namespace",
            name: "functions",
            tools: [{ type: "custom", name: "exec", description: "Execute native host tools" }],
          },
        ],
      },
    };
    const responsesToolCatalog = new ResponsesNativeToolCatalog(responsesSource);
    const responsesToolExecutor = new ResponsesNativeToolExecutor({
      call: async (selection) => {
        selected.push(selection);
        return {
          callId: "call-native",
          outputType: "custom_tool_call_output",
          output: [{ type: "input_text", text: "native-ok" }],
          rawItem: {
            type: "custom_tool_call_output",
            call_id: "call-native",
            output: [{ type: "input_text", text: "native-ok" }],
          },
        };
      },
    });
    const handle = createOmniCodexMcpServer({
      appServer,
      responsesToolCatalog,
      responsesToolExecutor,
    });
    const [clientTransport, serverTransport] = InMemoryTransport.createLinkedPair();
    const client = new Client({ name: "responses-test-client", version: "1.0.0" });
    await handle.server.connect(serverTransport);
    await client.connect(clientTransport);

    const listed = await client.listTools();
    const nativeCustom = listed.tools.find(
      (tool) => objectValue(tool._meta?.omnicodex).nativeName === "exec",
    );
    if (nativeCustom === undefined) throw new Error("missing custom native tool");
    const result = await client.callTool({
      name: nativeCustom.name,
      arguments: { input: 'text("native-ok")' },
    });
    expect(result.isError).not.toBe(true);
    expect(selected).toEqual([
      {
        kind: "custom",
        name: "exec",
        namespace: "functions",
        arguments: 'text("native-ok")',
      },
    ]);

    await client.close();
    await handle.server.close();
  });

  it("uses one collision-free registry for full listing and generic reachability", async () => {
    const calls: unknown[] = [];
    const appServer = {
      request: async <T>(method: string, params: unknown): Promise<T> => {
        if (method === "mcpServerStatus/list") {
          return {
            data: [
              {
                name: "demo",
                tools: {
                  shared: {
                    name: "shared",
                    inputSchema: {
                      type: "object",
                      properties: { downstream: { type: "boolean" } },
                      required: ["downstream"],
                    },
                  },
                },
              },
            ],
            nextCursor: null,
          } as T;
        }
        if (method === "thread/start") return { thread: { id: "direct-thread" } } as T;
        if (method === "mcpServer/tool/call") {
          const value = objectValue(params);
          calls.push({
            route: "downstream",
            server: value.server,
            tool: value.tool,
            args: value.arguments,
          });
          return { content: [{ type: "text", text: "downstream-ok" }] } as T;
        }
        throw new Error(`unexpected method ${method}`);
      },
    };
    const responsesSource = {
      snapshot: {
        refreshedAtUnixMs: 1,
        requestCount: 1,
        tools: [
          {
            type: "function",
            name: "shared",
            parameters: {
              type: "object",
              properties: { response: { type: "string" } },
              required: ["response"],
            },
          },
        ],
      },
      call: async (selection: unknown) => {
        calls.push({ route: "responses", selection });
        return { callId: "call-r", outputType: "function_call_output", output: "r", rawItem: {} };
      },
      callMcp: async (server: string, tool: string, args: unknown) => {
        throw new Error(`Responses bridge must not call ${server}/${tool}: ${String(args)}`);
      },
    };
    const responsesToolCatalog = new ResponsesNativeToolCatalog(responsesSource);
    const responsesToolExecutor = new ResponsesNativeToolExecutor(responsesSource);
    const handle = createOmniCodexMcpServer({
      appServer,
      responsesToolCatalog,
      responsesToolExecutor,
      surface: "full",
    });
    const [clientTransport, serverTransport] = InMemoryTransport.createLinkedPair();
    const client = new Client({ name: "registry-test-client", version: "1.0.0" });
    await handle.server.connect(serverTransport);
    await client.connect(clientTransport);

    const listed = await client.listTools();
    const shared = listed.tools.filter(
      (tool) => objectValue(tool._meta?.omnicodex).originalName === "shared",
    );
    expect(shared).toHaveLength(2);
    expect(new Set(shared.map((tool) => tool.name)).size).toBe(2);
    expect(shared.map((tool) => tool.name)).not.toContain("shared");
    const responses = shared.find(
      (tool) => objectValue(tool._meta?.omnicodex).source === "codex_responses_runtime",
    );
    const downstream = shared.find(
      (tool) => objectValue(tool._meta?.omnicodex).source === "codex_app_server_mcp",
    );
    if (responses === undefined || downstream === undefined) throw new Error("missing aliases");
    expect(responses.inputSchema).toEqual({
      type: "object",
      properties: { response: { type: "string" } },
      required: ["response"],
    });
    expect(downstream.inputSchema).toEqual({
      type: "object",
      properties: { downstream: { type: "boolean" } },
      required: ["downstream"],
    });

    expect(listed.tools.map((tool) => tool.name)).not.toEqual(
      expect.arrayContaining(["search_native_tools", "call_native_tool", "app_server_rpc"]),
    );
    await client.close();
    await handle.server.close();

    const compatHandle = createOmniCodexMcpServer({
      appServer,
      responsesToolCatalog: new ResponsesNativeToolCatalog(responsesSource),
      responsesToolExecutor,
      surface: "compat",
    });
    const [compatClientTransport, compatServerTransport] = InMemoryTransport.createLinkedPair();
    const compatClient = new Client({ name: "generic-registry-client", version: "1.0.0" });
    await compatHandle.server.connect(compatServerTransport);
    await compatClient.connect(compatClientTransport);
    await compatClient.listTools();
    const searched = await compatClient.callTool({
      name: "search_native_tools",
      arguments: { query: "shared" },
    });
    const searchedTools = objectValue(searched.structuredContent).tools;
    expect(
      Array.isArray(searchedTools) ? searchedTools.map((item) => objectValue(item).name) : [],
    ).toEqual(expect.arrayContaining([responses.name, downstream.name]));
    const searchResults = Array.isArray(searchedTools)
      ? searchedTools.map((item) => objectValue(item))
      : [];
    expect(searchResults.every((item) => typeof item.toolId === "string")).toBe(true);
    await compatClient.callTool({
      name: "call_native_tool",
      arguments: { name: responses.name, arguments: { response: "ok" } },
    });
    await compatClient.callTool({
      name: "call_native_tool",
      arguments: {
        toolId: objectValue(searchResults.find((item) => item.name === downstream.name)).toolId,
        arguments: { downstream: true },
      },
    });
    expect(calls).toEqual([
      {
        route: "responses",
        selection: { kind: "function", name: "shared", arguments: { response: "ok" } },
      },
      { route: "downstream", server: "demo", tool: "shared", args: { downstream: true } },
    ]);

    await compatClient.close();
    await compatHandle.server.close();
  });

  it("keeps compat listing stable while generic calls reach collision-resolved tools", async () => {
    const selected: unknown[] = [];
    const appServer = {
      request: async <T>(method: string): Promise<T> => {
        if (method === "mcpServerStatus/list") return { data: [], nextCursor: null } as T;
        throw new Error(`unexpected method ${method}`);
      },
    };
    const source = {
      snapshot: {
        refreshedAtUnixMs: 1,
        requestCount: 1,
        tools: [
          {
            type: "custom",
            name: "native_custom",
            description: "Custom native call",
          },
        ],
      },
      call: async (selection: unknown) => {
        selected.push(selection);
        return {
          callId: "custom",
          outputType: "custom_tool_call_output",
          output: "ok",
          rawItem: {},
        };
      },
    };
    const responsesToolCatalog = new ResponsesNativeToolCatalog(source);
    const handle = createOmniCodexMcpServer({
      appServer,
      responsesToolCatalog,
      responsesToolExecutor: new ResponsesNativeToolExecutor(source),
      surface: "compat",
    });
    const [clientTransport, serverTransport] = InMemoryTransport.createLinkedPair();
    const client = new Client({ name: "compat-registry-client", version: "1.0.0" });
    await handle.server.connect(serverTransport);
    await client.connect(clientTransport);

    expect((await client.listTools()).tools.map((tool) => tool.name)).toEqual([
      "search_native_tools",
      "call_native_tool",
      "app_server_rpc",
    ]);
    const search = await client.callTool({
      name: "search_native_tools",
      arguments: { query: "native_custom" },
    });
    const tools = objectValue(search.structuredContent).tools;
    const name = Array.isArray(tools) ? objectValue(tools[0]).name : undefined;
    if (typeof name !== "string") throw new Error("generic search did not return a name");
    await client.callTool({
      name: "call_native_tool",
      arguments: { name, input: "payload" },
    });
    expect(selected).toEqual([{ kind: "custom", name: "native_custom", arguments: "payload" }]);

    await client.close();
    await handle.server.close();
  });

  it("removes a downstream fallback wrapper before fake runtime dispatch", async () => {
    const calls: Array<{ method: string; params: unknown }> = [];
    const appServer = {
      request: async <T>(method: string, params: unknown): Promise<T> => {
        calls.push({ method, params });
        if (method === "mcpServerStatus/list") {
          return {
            data: [
              {
                name: "schema-server",
                tools: {
                  flexible: { name: "flexible", inputSchema: { type: "string" } },
                },
              },
            ],
            nextCursor: null,
          } as T;
        }
        if (method === "thread/start") return { thread: { id: "fake-thread" } } as T;
        if (method === "mcpServer/tool/call") {
          return { content: [{ type: "text", text: "fake-ok" }] } as T;
        }
        throw new Error(`unexpected method ${method}`);
      },
    };
    const handle = createOmniCodexMcpServer({ appServer, surface: "full" });
    const [clientTransport, serverTransport] = InMemoryTransport.createLinkedPair();
    const client = new Client({ name: "schema-wrapper-client", version: "1.0.0" });
    await handle.server.connect(serverTransport);
    await client.connect(clientTransport);

    const tool = (await client.listTools()).tools[0];
    if (tool === undefined) throw new Error("missing fallback tool");
    expect(tool.inputSchema).toEqual({
      type: "object",
      properties: { arguments: { type: "object", additionalProperties: true } },
      required: ["arguments"],
      additionalProperties: false,
    });
    await client.callTool({
      name: tool.name,
      arguments: { arguments: { exact: [1, true, null] } },
    });
    expect(calls.at(-1)).toEqual({
      method: "mcpServer/tool/call",
      params: {
        server: "schema-server",
        threadId: "fake-thread",
        tool: "flexible",
        arguments: { exact: [1, true, null] },
      },
    });

    await client.close();
    await handle.server.close();
  });

  it("keeps model and unclassified native targets unreachable through generic calls", async () => {
    const selected: unknown[] = [];
    const source = {
      snapshot: {
        refreshedAtUnixMs: 1,
        requestCount: 1,
        tools: [
          {
            type: "namespace",
            name: "collaboration",
            tools: [
              {
                type: "function",
                name: "spawn_agent",
                parameters: { type: "object", properties: { task_name: { type: "string" } } },
              },
            ],
          },
          { type: "future_native_tool", name: "unclassified" },
        ],
      },
      call: async (selection: unknown) => {
        selected.push(selection);
        return { callId: "forbidden", outputType: "function_call_output", output: "", rawItem: {} };
      },
    };
    const appServer = {
      request: async <T>(): Promise<T> => ({ data: [], nextCursor: null }) as T,
    };
    const handle = createOmniCodexMcpServer({
      appServer,
      responsesToolCatalog: new ResponsesNativeToolCatalog(source),
      responsesToolExecutor: new ResponsesNativeToolExecutor(source),
      surface: "compat",
    });
    const [clientTransport, serverTransport] = InMemoryTransport.createLinkedPair();
    const client = new Client({ name: "generic-policy-client", version: "1.0.0" });
    await handle.server.connect(serverTransport);
    await client.connect(clientTransport);
    await client.listTools();

    const search = await client.callTool({ name: "search_native_tools", arguments: {} });
    const values = objectValue(search.structuredContent).tools;
    const results = Array.isArray(values) ? values.map((item) => objectValue(item)) : [];
    const model = results.find((item) => item.nativeName === "spawn_agent");
    const unknown = results.find((item) => item.nativeName === "unclassified");
    const modelResult = await client.callTool({
      name: "call_native_tool",
      arguments: { name: model?.name, arguments: { task_name: "worker", invokesModel: true } },
    });
    const unknownResult = await client.callTool({
      name: "call_native_tool",
      arguments: { name: unknown?.name, payload: null },
    });
    expect(modelResult.isError).toBe(true);
    expect(unknownResult.isError).toBe(true);
    expect(selected).toEqual([]);

    await client.close();
    await handle.server.close();
  });

  it("pages the complete full registry with a revision-bound cursor", async () => {
    const tools = Object.fromEntries(
      Array.from({ length: 101 }, (_, index) => [
        `tool_${String(index).padStart(3, "0")}`,
        { name: `tool_${String(index).padStart(3, "0")}`, inputSchema: { type: "object" } },
      ]),
    );
    const appServer = {
      request: async <T>(): Promise<T> =>
        ({ data: [{ name: "paged", tools }], nextCursor: null }) as T,
    };
    const handle = createOmniCodexMcpServer({ appServer, surface: "full" });
    const [clientTransport, serverTransport] = InMemoryTransport.createLinkedPair();
    const client = new Client({ name: "paging-client", version: "1.0.0" });
    await handle.server.connect(serverTransport);
    await client.connect(clientTransport);

    const first = await client.listTools();
    expect(first.tools).toHaveLength(100);
    expect(first.nextCursor).toEqual(expect.any(String));
    const second = await client.listTools({ cursor: first.nextCursor });
    expect(second.tools).toHaveLength(1);
    expect(second.nextCursor).toBeUndefined();
    expect(new Set([...first.tools, ...second.tools].map((tool) => tool.name)).size).toBe(101);

    await client.close();
    await handle.server.close();
  });

  it("emits tools/list_changed when the full registry revision changes", async () => {
    let nativeTools: ResponsesNativeToolSpec[] = [
      { type: "function", name: "first", parameters: { type: "object" } },
    ];
    const source = {
      get snapshot() {
        return { refreshedAtUnixMs: 1, requestCount: 1, tools: nativeTools };
      },
    };
    const appServer = {
      request: async <T>(): Promise<T> => ({ data: [], nextCursor: null }) as T,
    };
    const handle = createOmniCodexMcpServer({
      appServer,
      responsesToolCatalog: new ResponsesNativeToolCatalog(source),
      surface: "full",
    });
    const [clientTransport, serverTransport] = InMemoryTransport.createLinkedPair();
    const client = new Client({ name: "list-change-client", version: "1.0.0" });
    await handle.server.connect(serverTransport);
    await client.connect(clientTransport);
    await client.listTools();
    const changed = new Promise<void>((resolveChanged) => {
      client.setNotificationHandler(ToolListChangedNotificationSchema, async () =>
        resolveChanged(),
      );
    });

    nativeTools = [
      ...nativeTools,
      { type: "function", name: "second", parameters: { type: "object" } },
    ];
    await handle.refresh();
    await changed;
    expect((await client.listTools()).tools.map((tool) => tool.name)).toEqual(
      expect.arrayContaining(["first", "second"]),
    );

    await client.close();
    await handle.server.close();
  });
});

function objectValue(value: unknown): Record<string, unknown> {
  if (typeof value !== "object" || value === null || Array.isArray(value)) return {};
  return value as Record<string, unknown>;
}
