import { createHash } from "node:crypto";
import type { Tool } from "@modelcontextprotocol/sdk/types.js";
import { type AppServerRpcClient, isModelInvokingAppServerMethod } from "./native-tool-catalog.js";

export type JsonSchema = boolean | Record<string, unknown>;

export interface AppServerSchemaSource {
  loadClientRequestSchema(): Promise<Record<string, unknown>>;
}

export interface AppServerMethodDescriptor {
  readonly exposedName: string;
  readonly method: string;
  readonly invokesModel: boolean;
  readonly requestTitle: string | undefined;
  readonly tool: Tool;
}

export interface AppServerMethodCatalogSnapshot {
  readonly refreshedAtUnixMs: number;
  readonly methods: readonly AppServerMethodDescriptor[];
  readonly schemaDigest: string;
}

export interface AppServerMethodCatalogOptions {
  readonly reservedNames?: readonly string[];
}

/**
 * Converts the protocol schema generated by the installed Codex binary into
 * first-class MCP tools. No checked-in method census is treated as complete.
 */
export class AppServerMethodCatalog {
  readonly #source: AppServerSchemaSource;
  readonly #reservedNames: ReadonlySet<string>;
  #snapshot: AppServerMethodCatalogSnapshot = {
    refreshedAtUnixMs: 0,
    methods: [],
    schemaDigest: "",
  };

  constructor(source: AppServerSchemaSource, options: AppServerMethodCatalogOptions = {}) {
    this.#source = source;
    this.#reservedNames = new Set(options.reservedNames ?? []);
  }

  get snapshot(): AppServerMethodCatalogSnapshot {
    return this.#snapshot;
  }

  async refresh(): Promise<AppServerMethodCatalogSnapshot> {
    const schema = await this.#source.loadClientRequestSchema();
    const next = parseAppServerMethodCatalog(schema, this.#reservedNames);
    this.#snapshot = {
      ...next,
      refreshedAtUnixMs: Date.now(),
    };
    return this.#snapshot;
  }
}

export class AppServerMethodExecutor {
  readonly #client: AppServerRpcClient;

  constructor(client: AppServerRpcClient) {
    this.#client = client;
  }

  async call(descriptor: AppServerMethodDescriptor, argumentsValue: unknown): Promise<unknown> {
    const args = isObject(argumentsValue) ? { ...argumentsValue } : {};
    if (descriptor.invokesModel) {
      if (args.invokesModel !== true) {
        throw new Error(`App Server method ${descriptor.method} requires invokesModel=true`);
      }
      delete args.invokesModel;
    }
    return this.#client.request(descriptor.method, args);
  }
}

export function parseAppServerMethodCatalog(
  schema: Record<string, unknown>,
  reservedNames: ReadonlySet<string> = new Set(),
): Omit<AppServerMethodCatalogSnapshot, "refreshedAtUnixMs"> {
  const definitions = isObject(schema.definitions) ? schema.definitions : {};
  const variants = Array.isArray(schema.oneOf) ? schema.oneOf : [];
  const descriptors: AppServerMethodDescriptor[] = [];

  for (const variantValue of variants) {
    if (!isObject(variantValue)) {
      continue;
    }
    const properties = isObject(variantValue.properties) ? variantValue.properties : {};
    const methodSchema = isObject(properties.method) ? properties.method : {};
    const method =
      Array.isArray(methodSchema.enum) && typeof methodSchema.enum[0] === "string"
        ? methodSchema.enum[0]
        : undefined;
    if (method === undefined || method.length === 0) {
      continue;
    }

    const paramsSchema = bundleParamsSchema(properties.params, definitions);
    const invokesModel = isModelInvokingAppServerMethod(method);
    const inputSchema = invokesModel ? requireModelAcknowledgement(paramsSchema) : paramsSchema;
    const requestTitle = typeof variantValue.title === "string" ? variantValue.title : undefined;
    const description =
      typeof variantValue.description === "string"
        ? variantValue.description
        : `Call the installed Codex App Server method ${method}.`;
    const exposedName = appServerToolName(method, reservedNames);
    const tool = {
      name: exposedName,
      ...(requestTitle === undefined ? {} : { title: requestTitle }),
      description,
      inputSchema,
      _meta: {
        omnicodex: {
          source: "codex_app_server_schema",
          originalName: method,
          exposedName,
          invokesModel,
        },
      },
    } as unknown as Tool;
    descriptors.push({ exposedName, method, invokesModel, requestTitle, tool });
  }

  descriptors.sort((left, right) => left.method.localeCompare(right.method, "en"));
  const schemaDigest = createHash("sha256").update(JSON.stringify(schema), "utf8").digest("hex");
  return { methods: descriptors, schemaDigest };
}

function bundleParamsSchema(
  rawParamsSchema: unknown,
  definitions: Record<string, unknown>,
): Record<string, unknown> {
  const root = cloneSchema(rawParamsSchema);
  if (!isObject(root)) {
    return { type: "object", additionalProperties: true };
  }
  const referencedNames = new Set<string>();
  collectDefinitionRefs(root, definitions, referencedNames);
  const bundledDefinitions: Record<string, unknown> = {};
  for (const name of [...referencedNames].sort((left, right) => left.localeCompare(right, "en"))) {
    const definition = definitions[name];
    if (definition !== undefined) {
      bundledDefinitions[name] = rewriteDefinitionRefs(cloneSchema(definition));
    }
  }
  const rewritten = rewriteDefinitionRefs(root);
  return {
    ...rewritten,
    type: "object",
    ...(Object.keys(bundledDefinitions).length === 0 ? {} : { $defs: bundledDefinitions }),
  };
}

function collectDefinitionRefs(
  value: unknown,
  definitions: Record<string, unknown>,
  names: Set<string>,
): void {
  if (Array.isArray(value)) {
    for (const item of value) {
      collectDefinitionRefs(item, definitions, names);
    }
    return;
  }
  if (!isObject(value)) {
    return;
  }
  const reference = value.$ref;
  if (typeof reference === "string" && reference.startsWith("#/definitions/")) {
    const name = decodeURIComponent(reference.slice("#/definitions/".length));
    if (!names.has(name)) {
      names.add(name);
      collectDefinitionRefs(definitions[name], definitions, names);
    }
  }
  for (const nested of Object.values(value)) {
    collectDefinitionRefs(nested, definitions, names);
  }
}

function rewriteDefinitionRefs<T>(value: T): T {
  if (Array.isArray(value)) {
    return value.map((item) => rewriteDefinitionRefs(item)) as T;
  }
  if (!isObject(value)) {
    return value;
  }
  const result: Record<string, unknown> = {};
  for (const [key, nested] of Object.entries(value)) {
    if (key === "$ref" && typeof nested === "string" && nested.startsWith("#/definitions/")) {
      result[key] = `#/$defs/${nested.slice("#/definitions/".length)}`;
    } else {
      result[key] = rewriteDefinitionRefs(nested);
    }
  }
  return result as T;
}

function requireModelAcknowledgement(schema: Record<string, unknown>): Record<string, unknown> {
  if (schema.type === "object" || isObject(schema.properties)) {
    const properties = isObject(schema.properties) ? schema.properties : {};
    const required = Array.isArray(schema.required)
      ? schema.required.filter((item): item is string => typeof item === "string")
      : [];
    return {
      ...schema,
      properties: {
        ...properties,
        invokesModel: {
          type: "boolean",
          const: true,
          description: "Must be true because this App Server method invokes the Codex model.",
        },
      },
      required: [...new Set([...required, "invokesModel"])],
    };
  }
  return {
    type: "object",
    required: ["params", "invokesModel"],
    properties: {
      params: schema,
      invokesModel: { type: "boolean", const: true },
    },
  };
}

function appServerToolName(method: string, reservedNames: ReadonlySet<string>): string {
  const sanitized = method.replace(/[^A-Za-z0-9_.-]+/g, "_") || "unknown";
  let name = `codex__app_server__${sanitized}`;
  if (name.length > 128) {
    const digest = createHash("sha256").update(method, "utf8").digest("hex").slice(0, 12);
    name = `${name.slice(0, 113)}__${digest}`;
  }
  if (!reservedNames.has(name)) {
    return name;
  }
  const digest = createHash("sha256")
    .update(`reserved\n${method}`, "utf8")
    .digest("hex")
    .slice(0, 12);
  return `${name.slice(0, 113)}__${digest}`;
}

function cloneSchema<T>(value: T): T {
  if (value === undefined) {
    return value;
  }
  return structuredClone(value);
}

function isObject(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}
